server
{
    listen 80;
    server_name itra.com.cn www.itra.com.cn itra.wsl;
    index index.php index.html index.htm;
    root /home/wwwroot/xmt/web;

    include proxy-pass-php.conf;

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires 30d;
    }

    location ~ .*\.(js|css)?$
    {
        expires 12h;
    }

    location ~ /\.
    {
        deny all;
    }

    access_log /home/wwwlogs/itra.com.cn.log;
}
