<?php

/**
 * @file
 * XMT syndication helpers.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert() for node.
 */
function xmt_syndicate_node_insert(NodeInterface $node) {
  if ($node->bundle() !== 'article') {
    return;
  }
  if (!empty($node->xmt_skip_syndicate)) {
    return;
  }
  /** @var \Drupal\xmt_syndicate\Service\SyndicateService $service */
  $service = \Drupal::service('xmt_syndicate.syndicate');
  $service->syndicateToXmt($node);
}

/**
 * Implements hook_ENTITY_TYPE_update() for node.
 */
function xmt_syndicate_node_update(NodeInterface $node) {
  if ($node->bundle() !== 'article') {
    return;
  }
  if (!empty($node->xmt_skip_syndicate)) {
    return;
  }
  /** @var \Drupal\xmt_syndicate\Service\SyndicateService $service */
  $service = \Drupal::service('xmt_syndicate.syndicate');
  $service->syndicateToXmt($node);
}
